In [53]:
import pickle
import numpy as np
import copy

In [54]:
# read my pickle
# data = pickle.load(open("individuals_friendships_utilities.p","rb"))
# characteristics, connectivity, utilities = data

g_list = pickle.load(open("g_list.pkl", "rb"))

In [55]:
print(g_list[0])
print(np.sum(g_list[0]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
305.0


In [56]:
small = np.array([[0,1,1,0],
                 [1,0,1,0],
                 [0,0,0,0],
                 [0,0,0,0]])
print(small)
print(np.sum(small))

[[0 1 1 0]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
4


In [57]:
np.sum(small)

4

In [58]:
small

array([[0, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [87]:
DENX2, RCHDEN, RELDEN, PTCMUT, PTCASY, RHO2 = ana_dyads(small)

In [88]:
print(ana_dyads(small))

(0.3333333333333333, 0.5, 0.1, 0.3333333333333333, 0.6666666666666666, 0.35714285714285715)


In [61]:
def ana_dyads(connectivity):
    # Calculate:
    # density (DENX2),
    # density at maximum reach (RCHDEN),
    # relative density (RELDEN),
    # proportion symmetric dyads (PTCMUT), 
    # asymmetric dyads (PTCASY), and 
    # mutuality index (RHO2)
    
    nodes = connectivity.shape[0]
    mutual_d = 0
    asym_d = 0
    out_degrees = []
    
    
    #density DENX2
    DENX2 = np.sum(connectivity)/(nodes*(nodes-1))
    
    
    # density at maximum reach RCHDEN
    
    # define the function to tranfer adjacency matrix to reachability matrix  
    # Prints reachability matrix of graph[][] using Floyd Warshall algorithm 
    # function found on https://www.geeksforgeeks.org/transitive-closure-of-a-graph/
    reachability = copy.deepcopy(connectivity)
    '''reach[][] will be the output matrix that will finally 
    have reachability values. 
    Initialize the solution matrix same as input graph matrix'''
    reach =[i[:] for i in reachability] 
    '''Add all vertices one by one to the set of intermediate 
    vertices. 
    ---> Before start of a iteration, we have reachability value 
    for all pairs of vertices such that the reachability values 
    consider only the vertices in set  
    {0, 1, 2, .. k-1} as intermediate vertices. 
    ----> After the end of an iteration, vertex no. k is 
    added to the set of intermediate vertices and the  
    set becomes {0, 1, 2, .. k}'''
    for k in range(nodes): 
              
        # Pick all vertices as source one by one 
        for i in range(nodes): 
                  
            # Pick all vertices as destination for the 
            # above picked source 
            for j in range(nodes): 
                      
                # If vertex k is on a path from i to j,  
                    # then make sure that the value of reach[i][j] is 1 
                reach[i][j] = reach[i][j] or (reach[i][k] and reach[k][j]) 
    
    RCHDEN = np.sum(reach)/(nodes*(nodes-1))
    
    
    # relative density RELDEN
    RELDEN = np.sum(connectivity)/(10*nodes)


    # create upper triangular matrix with 2's on mutual dyads, 1's on asymmetric dyads and count occurrence
    added_up = np.triu(connectivity + np.transpose(connectivity))
    mutual_d = np.count_nonzero(added_up == 2)
    asym_d = np.count_nonzero(added_up == 1)
    total_d = mutual_d + asym_d
    
    # calculate proportion symmetric dyads (PTCMUT) and asymmetric dyads (PTCASY)
    PTCMUT = mutual_d / total_d
    PTCASY = asym_d / total_d
    
    
    # count total out_degree connections
    out_degree = connectivity.sum()
    # take the sum of squares of the out degree connections per individual (row)
    sum_squares_out = (connectivity.sum(axis=1)**2).sum()
    
    # calculate mutuality index (RHO2) (according to Katz and Powell’s (1955))
    RHO2 = (2*(nodes - 1)**2 * mutual_d - sum_out_degrees**2 + sum_squares_out) / (sum_out_degrees*(nodes - 1)**2 - sum_out_degrees**2 + sum_squares_out)

    
    return DENX2, RCHDEN, RELDEN, PTCMUT, PTCASY, RHO2
    

In [89]:
ana_dyads(connectivity)

(0.0496969696969697,
 0.7777777777777778,
 0.492,
 0.37815126050420167,
 0.6218487394957983,
 0.5251843116442362)