In [5]:
import pickle
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
# read my pickle
# data = pickle.load(open("individuals_friendships_utilities.p","rb"))
# characteristics, connectivity, utilities = data

g_list = pickle.load(open("g_list.pkl", "rb"))
X_list = pickle.load(open("X_list.pkl", "rb"))

ModuleNotFoundError: No module named 'numpy'

In [1]:
connectivity = g_list[1]
print(connectivity.shape)
# print(connectivity)
characteristics = X_list[1]
charac_short = characteristics[:,0:3]
print(charac_short.shape)
# print(charac_short)

NameError: name 'g_list' is not defined

In [276]:
# analyse_network(connectivity, characteristics)

In [68]:
small = np.array([[0,1,1,0],
                 [1,0,1,0],
                 [0,0,0,0],
                 [0,0,0,0]])
print(small)
print(np.sum(small))

charac_mini = charac_short[0:4]
print(charac_mini)

[[0 1 1 0]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
4
[[ 2  1 10]
 [ 1  1  7]
 [ 2  1 12]
 [ 1  1  9]]


In [40]:
small5 = np.array([[0,1,1,1,1],
                 [1,0,1,1,0],
                 [1,1,0,0,0],
                 [0,0,0,0,0],
                  [1,0,1,1,0]])
print(small5)
print(np.sum(small5))

charac_mini5 = charac_short[0:5]
print(charac_mini5)

[[0 1 1 1 1]
 [1 0 1 1 0]
 [1 1 0 0 0]
 [0 0 0 0 0]
 [1 0 1 1 0]]
12
[[ 2  1 10]
 [ 1  1  7]
 [ 2  1 12]
 [ 1  1  9]
 [ 1  1 11]]


In [86]:
analyse(small5, charac_mini5)

[[0 1 1 1 1]
 [1 0 1 1 0]
 [1 1 0 0 0]
 [0 0 0 0 0]
 [1 0 1 1 0]]
[4 3 2 0 3]
2.4
1.3564659966250536
[[0 2 2 1 2]
 [2 0 2 1 0]
 [2 2 0 0 1]
 [1 1 0 0 1]
 [2 0 1 1 0]]
[3 2 2 0 1]
[0.75       0.66666667 1.                nan 0.33333333]
5
[0.75, 0.6666666666666666, 1.0, 0.3333333333333333]
4
0.6875
0.23844839879707494
GROUP:  0 - 0
expect =  1.2000000000000002
observ =  2
seg ind =  -0.6666666666666664
GROUP:  0 - 0
expect =  0.0
observ =  0
seg ind =  nan
GROUP:  0 - 0
expect =  1.2000000000000002
observ =  2
seg ind =  -0.6666666666666664
GROUP:  0 - 1
expect =  2.4
observ =  3
seg ind =  -0.25000000000000006
GROUP:  0 - 1
expect =  1.2
observ =  1
seg ind =  0.16666666666666663
5
4
[[-0.3541666666666665, 0.345481748995354]]
GROUP:  1 - 0
expect =  0.0
observ =  0
seg ind =  nan
GROUP:  1 - 0
expect =  0.0
observ =  0
seg ind =  nan
GROUP:  1 - 0
expect =  0.0
observ =  0
seg ind =  nan
GROUP:  1 - 0
expect =  0.0
observ =  0
seg ind =  nan
GROUP:  1 - 0
expect =  0.0
observ =  0
seg 

/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:59: RuntimeWarning: invalid value encountered in true_divide
/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:138: RuntimeWarning: invalid value encountered in double_scalars
/Applications/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Applications/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Applications/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/Applications/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Applications/miniconda3/lib/python3.7/site-packag

([2.4, 1.3564659966250536],
 [0.6875, 0.23844839879707494],
 [0.6041666666666667, 0.2310528438835295],
 [[-0.3541666666666665, 0.345481748995354],
  [nan, nan],
  [-0.2499999999999999, 7.076311083754595e-17]])

In [12]:
# output:
# den_max_reach / density at maximum reach (RCHDEN): density of the reachability network 
# rel_den / relative density (RELDEN): amount of nodes divided by the maximum possible number of nodes
# p_symm_dyads / proportion symmetric dyads (PTCMUT): proportion of nodes that are reciprocal (counting once)
# mutuality_index / mutuality index (RHO2): Katz and Powell’s (1955) mutuality index. Measures the tendency for actors in a group to reciprocate choices.
den_max_reach, rel_den, p_symm_dyads, mutuality_index, clustering_coefficient = analyse_network(small)

In [99]:
import pickle
import numpy as np
import copy
import warnings
import math

def analyse(connectivity, characteristics):
    """
        Calculate mean and standard deviation (output in tuples [mean,sd]) of following measures:
        
        - degree
        - mut_prop
        - cluster_coef
        - segreg_ind    > list with length of the amount of characteristics (3 for sex, race, grade)
        
        INPUT: 
        - connectivity matrix with row-students nominating column-students as friends
        - characteristics matrix with row per student, with integers indicating every group for each characteristic (sex, race, grade)
    """
    
    # get amount of nodes and list of out going dyads for every individual
    nodes = connectivity.shape[0]
    out_d = np.count_nonzero(connectivity, axis=1)
    
    
    # determine degree nodes (outgoing connections)
    mean_degree = np.mean(out_d)
    std_degree = np.std(out_d)
    degree = [mean_degree, std_degree]

    
    # determine the mutual dyads proportion
    # create matrix with 2's on mutual dyads, 1's on asymmetric dyads and count occurrence
    added_up = connectivity + np.transpose(connectivity)
    mutual_d = np.count_nonzero(added_up == 2, axis=1)
    mut_prop = mutual_d / out_d
    # remove 'nan' individuals (with no out-going connections) from list
    mut_prop = [value for value in mut_prop if not math.isnan(value)]
    # calculate mean+std mutual dyads proportion
    mean_mut_prop = np.mean(mut_prop)
    std_mut_prop = np.std(mut_prop)
    mut_prop = [mean_mut_prop, std_mut_prop]
    
    
    # determine the local clustering coefficient
    clustering_coefficients = []
    for n_node, connections in enumerate(connectivity):
        # the amount of neighbours each node has
        n_neighbours = np.sum(connectivity[n_node])
        # only consider nodes with at least 2 neighbours
        if n_neighbours >= 2:
            # matrix of the nodes that are both neighbours of the node considered
            neighbour_matrix = np.dot(np.transpose([connectivity[n_node]]),[connectivity[n_node]])
            # the amount of connections between neighbours
            neighbour_connections = np.sum(connectivity*neighbour_matrix)
            # the amount of connections between neighbours divided by the possible amount of connections
            clustering_coefficients.append(neighbour_connections / (n_neighbours*(n_neighbours-1)))
    # calculate mean+std clustering coefficient
    mean_cluster_coef = np.mean(clustering_coefficients)
    std_cluster_coef = np.std(clustering_coefficients)
    cluster_coef = [mean_cluster_coef, std_cluster_coef]

    
    # determine the segregation index per characteristic (sex, race, grade)
    segreg_ind = []
    # iterate through different characteristics (sex, race, grade)
    for i in range(characteristics.shape[1]):
        # get different groups of this characteristic in dataset
        characs = sorted(list(set(characteristics[:,i])))
        amount = len(characs)
        # for every characteristic own tuple for mean and std
        segreg_ind_charac = []
        # iterate through different groups of this characteristic
        for j in range(amount):
            # indicate indices of members this group and save size group
            indices = np.where(characteristics[:,i] == characs[j])[0]
            # calculate ratio out-group individuals
            ratio_diff = 1 - len(indices) / nodes
            # create a submatrix of all nominations from this group and save amount
            submat_trait = connectivity[np.ix_(indices,)]
            # create submatrix outgoing connections to individuals different group
            mask = np.ones(connectivity.shape[0], np.bool)
            mask[indices] = 0
            submat_diff = submat_trait[:,mask]
            # calculate segregation index per individual of this group for this characteristic
            for ind in range(len(indices)):
                expect_out = submat_trait[ind].sum() * ratio_diff
                observ_out = submat_diff[ind].sum()
                seg_ind = (expect_out - observ_out) / expect_out
                if seg_ind < -1:
                    seg_ind = -1
                segreg_ind_charac.append(seg_ind)
        # remove 'nan' individuals from list
        segreg_ind_charac = [value for value in segreg_ind_charac if not math.isnan(value)]
        # calculate mean+std segregation index this characteristic
        mean_segreg_ind_charac = np.mean(segreg_ind_charac)
        std_segreg_ind_charac = np.std(segreg_ind_charac)
        segreg_ind.append([mean_segreg_ind_charac, std_segreg_ind_charac])
    
    
    return degree, mut_prop, cluster_coef, segreg_ind

In [98]:
analyse(connectivity, charac_short)

1.2110091743119267
3.0
-1.477272727272727
0.4036697247706422
1.0
-1.477272727272727
2.4220183486238533
5.0
-1.0643939393939392
2.4220183486238533
5.0
-1.0643939393939392
0.6605504587155964
2.0
-2.0277777777777777
0.3669724770642202
1.0
-1.7249999999999999
0.07339449541284404
1.0
-12.625
0.29357798165137616
1.0
-2.40625
0.7339449541284404
2.0
-1.7249999999999999
0.44036697247706424
1.0
-1.2708333333333333
0.29357798165137616
1.0
-2.40625
0.3669724770642202
1.0
-1.7249999999999999
0.29357798165137616
1.0
-2.40625
0.29357798165137616
1.0
-2.40625
0.6605504587155964
2.0
-2.0277777777777777
0.22018348623853212
1.0
-3.5416666666666665
0.3669724770642202
1.0
-1.7249999999999999


/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in true_divide
/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:94: RuntimeWarning: invalid value encountered in double_scalars


([4.10091743119266, 2.6783020573888945],
 [0.4622809193121693, 0.3124947738802088],
 [0.32442072614486406, 0.20200116408940086],
 [[0.2626266832126207, 0.5908324508788445],
  [0.5275140079778401, 0.7846603477598104],
  [0.6720915330575545, 0.3640790183211239]])

In [92]:
analyse(connectivity, charac_short)

/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in true_divide
/Applications/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:97: RuntimeWarning: invalid value encountered in double_scalars


GROUP:  0 - 0
expect =  0.8073394495412844
observ =  0.0
seg ind =  1.0
GROUP:  0 - 0
expect =  0.0
observ =  0.0
seg ind =  nan
GROUP:  0 - 0
expect =  0.0
observ =  0.0
seg ind =  nan
GROUP:  0 - 0
expect =  2.0183486238532113
observ =  2.0
seg ind =  0.009090909090909255
GROUP:  0 - 0
expect =  3.6330275229357802
observ =  5.0
seg ind =  -0.3762626262626261
GROUP:  0 - 0
expect =  1.614678899082569
observ =  2.0
seg ind =  -0.23863636363636356
GROUP:  0 - 0
expect =  1.2110091743119267
observ =  3.0
seg ind =  -1.477272727272727
GROUP:  0 - 0
expect =  2.4220183486238533
observ =  4.0
seg ind =  -0.6515151515151514
GROUP:  0 - 0
expect =  3.229357798165138
observ =  4.0
seg ind =  -0.23863636363636356
GROUP:  0 - 0
expect =  2.0183486238532113
observ =  1.0
seg ind =  0.5045454545454546
GROUP:  0 - 0
expect =  0.0
observ =  0.0
seg ind =  nan
GROUP:  0 - 0
expect =  0.8073394495412844
observ =  1.0
seg ind =  -0.23863636363636356
GROUP:  0 - 0
expect =  2.4220183486238533
observ =  

GROUP:  2 - 0
expect =  1.5596330275229358
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  7.0183486238532105
observ =  2.0
seg ind =  0.7150326797385621
GROUP:  2 - 0
expect =  7.0183486238532105
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  7.798165137614679
observ =  2.0
seg ind =  0.7435294117647059
GROUP:  2 - 0
expect =  3.8990825688073394
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  1.5596330275229358
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  3.1192660550458715
observ =  1.0
seg ind =  0.6794117647058824
GROUP:  2 - 0
expect =  4.678899082568807
observ =  2.0
seg ind =  0.5725490196078431
GROUP:  2 - 0
expect =  7.798165137614679
observ =  1.0
seg ind =  0.8717647058823529
GROUP:  2 - 0
expect =  3.1192660550458715
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  3.1192660550458715
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  5.458715596330276
observ =  0.0
seg ind =  1.0
GROUP:  2 - 0
expect =  6.238532110091743
observ =  0.0
seg ind =

([4.10091743119266, 2.6783020573888945],
 [0.4622809193121693, 0.3124947738802088],
 [0.32442072614486406, 0.20200116408940086],
 [[0.2513419609903985, 0.6182915327030725],
  [0.26690926260746983, 1.7163940247543252],
  [0.6720915330575545, 0.3640790183211239]])